fix: wires extra vars correctly
mesosphere/konvoy-image-builder pull request #226
Opened 2022-01-31 22:09 UTC by faiq

**What problem does this PR solve?**:
Wires the values of `extra-vars` flag to the `builder` which is used for provisioning.
Also adds `extra-vars` flag to `build` and `generate` commands

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-NUMBER

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: wires extra vars correctly 
feat: add extra-vars to build and generate commands
```

2022-01-31 22:52 UTC, jkoelker approved these changes
\o/

2022-01-31 22:59 UTC, supershal requested changes
Thanks for fixing it.

2022-02-01 00:32 UTC, supershal approved these changes

2022-02-01 00:33 UTC, supershal commented
sorry. Clicked on "change requested" by mistake. approved the PR now

2022-02-02 18:53 UTC, merged