[D2IQ-88880] feat: adding skeleton for gcp command to build images (hidden)
mesosphere/konvoy-image-builder pull request #344
Opened 2022-05-18 15:23 UTC by alejandroEsc

**What problem does this PR solve?**:
This is the first part of allowing image building for gcp. This sets up the cli to do this, nothing more, I will be building on this as we go and for now it will remain hidden. 

**Which issue(s) does this PR fix?**:

* https://jira.d2iq.com/browse/D2IQ-88880

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2022-05-25 21:14 UTC, supershal requested changes

2022-05-25 21:14 UTC, supershal commented on cmd/konvoy-image/cmd/gcp.go
> +	gcpExample = "gpc ... images/azure/centos-7.yaml"
```suggestion
	gcpExample = "gcp ... images/gcp/centos-7.yaml"
```

2022-05-25 21:14 UTC, supershal commented on cmd/konvoy-image/cmd/gcp.go
> +	gFlags.userArgs.Azure = &app.AzureArgs{}
I am sure you want to add gcp flags here. :) . but wiring wise it looks ok. 
I think you can add the gcp subcommand and flags without hiding and fake/empty business logic. 
Next set of PRs can fill those logic. wdyt?

2022-05-26 17:04 UTC, dlipovetsky approved these changes
Review comments addressed, lgtm

2022-05-26 17:06 UTC, supershal approved these changes

2022-05-26 17:08 UTC, merged